## Numpy
-numerical python
-it works as creating arrays and mathematical operations and statistical operations

In [1]:
#importing numpy
import numpy as np

In [2]:
len(dir(np))

620

In [3]:
#creating an array
a1=np.array([1,2,3,4,5])
a1


array([1, 2, 3, 4, 5])

In [4]:
a1.ndim #to know dimensions

1

In [5]:
a1.size

5

In [6]:
a1.shape

(5,)

In [8]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
a=[7,9,8,7]
print(sum(a))

31


In [11]:
a3=np.array([1,2,34,5,6,7,8,79,3,8,1,7])
a4=a3.reshape(2,6)

In [13]:
a3.shape #how many in an array it prints

(12,)

In [14]:
a4.shape

(2, 6)

In [23]:
a4=a3.reshape(2,6)
a4

array([[ 1,  2, 34,  5,  6,  7],
       [ 8, 79,  3,  8,  1,  7]])

In [24]:
a4[1:2,5:7]

array([[7]])

In [25]:
a4[0:2,4:5]

array([[6],
       [1]])

In [26]:
a4[1:2]

array([[ 8, 79,  3,  8,  1,  7]])

In [39]:
a4

array([[ 1,  2, 34,  5,  6,  7],
       [ 8, 79,  3,  8,  1,  7]])

In [42]:
a4[1:2,1:6:2]

array([[79,  8,  7]])

In [48]:
a4[0:3,2:4]

array([[34,  5],
       [ 3,  8]])

In [49]:
a5=np.array([1,2,34,5,6,7,8,79,3,8,1,7,23,45,67,12,34,56,762,67])
a6=a5.

array([  1,   2,  34,   5,   6,   7,   8,  79,   3,   8,   1,   7,  23,
        45,  67,  12,  34,  56, 762,  67])

In [50]:
np.random.rand(1,10) #it gets positive values

array([[0.63086367, 0.54534091, 0.29562926, 0.01607165, 0.55065496,
        0.95457694, 0.5065531 , 0.4637199 , 0.08309867, 0.42982976]])

In [51]:
np.random.randn(1,10) #it gets negitive  values

array([[ 0.4809304 , -1.98613829, -0.39521674, -0.46000909,  0.8422535 ,
         1.71530601, -2.2901968 , -0.55402616, -0.1707591 ,  1.6296917 ]])

In [52]:
np.random.randint(1,100)

23

In [53]:
np.random.randint(1,100,10)

array([13,  4, 80,  3, 89,  9, 82, 79, 60, 68])

In [54]:
np.random.randint(81,100,100)

array([95, 90, 88, 85, 95, 83, 95, 83, 89, 81, 87, 89, 91, 82, 97, 98, 87,
       88, 86, 90, 83, 96, 81, 82, 98, 86, 97, 95, 92, 94, 91, 86, 83, 89,
       87, 99, 94, 81, 82, 98, 84, 96, 98, 97, 94, 90, 96, 99, 87, 91, 90,
       94, 82, 90, 82, 95, 91, 98, 88, 83, 88, 83, 93, 89, 98, 89, 98, 81,
       83, 99, 82, 90, 88, 96, 89, 93, 92, 98, 97, 93, 93, 82, 88, 81, 97,
       87, 98, 81, 83, 97, 90, 95, 88, 94, 94, 89, 87, 97, 88, 91])

In [60]:
a=np.random.randint(81,100,100)
for i in a:
    if i%2==0:
        print(i,end=',')

94,92,82,88,82,84,82,82,98,94,98,82,88,82,88,92,96,82,88,86,86,86,82,86,92,90,86,90,88,96,84,86,90,96,84,94,84,

In [59]:
a=np.random.randint(81,100,100)
for i in a:
    if i%2!=0:
        print(i,end=',')

95,97,89,97,89,85,95,93,87,95,81,87,99,99,93,93,89,85,95,87,97,93,89,81,85,85,95,99,95,83,93,83,85,91,81,87,99,91,91,91,83,93,95,95,95,95,91,89,83,81,95,93,97,93,89,

In [61]:
a[a%2==0]

array([94, 92, 82, 88, 82, 84, 82, 82, 98, 94, 98, 82, 88, 82, 88, 92, 96,
       82, 88, 86, 86, 86, 82, 86, 92, 90, 86, 90, 88, 96, 84, 86, 90, 96,
       84, 94, 84])

In [2]:
import numpy as np
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
import numpy as np
a4=np.ones((5,5),int)
a4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
import numpy as np
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
import numpy as np
a5=np.zeros((5,5))
a5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
import numpy as np
np.twos((2,5),int) #only works for one and two

AttributeError: module 'numpy' has no attribute 'twos'

In [12]:
np.hstack((a4,a5))

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [13]:
a4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
a5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.vsplit(a4,5)

[array([[1, 1, 1, 1, 1]]),
 array([[1, 1, 1, 1, 1]]),
 array([[1, 1, 1, 1, 1]]),
 array([[1, 1, 1, 1, 1]]),
 array([[1, 1, 1, 1, 1]])]

In [24]:
np.vsplit(a5,5)

[array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0.]])]

In [25]:
np.hsplit(a4,5)

[array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]]),
 array([[1],
        [1],
        [1],
        [1],
        [1]])]

In [31]:
np.vstack((a4,a5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.hstack((a4,a5))

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [28]:
np.linspace(1,1000,100)

array([   1.        ,   11.09090909,   21.18181818,   31.27272727,
         41.36363636,   51.45454545,   61.54545455,   71.63636364,
         81.72727273,   91.81818182,  101.90909091,  112.        ,
        122.09090909,  132.18181818,  142.27272727,  152.36363636,
        162.45454545,  172.54545455,  182.63636364,  192.72727273,
        202.81818182,  212.90909091,  223.        ,  233.09090909,
        243.18181818,  253.27272727,  263.36363636,  273.45454545,
        283.54545455,  293.63636364,  303.72727273,  313.81818182,
        323.90909091,  334.        ,  344.09090909,  354.18181818,
        364.27272727,  374.36363636,  384.45454545,  394.54545455,
        404.63636364,  414.72727273,  424.81818182,  434.90909091,
        445.        ,  455.09090909,  465.18181818,  475.27272727,
        485.36363636,  495.45454545,  505.54545455,  515.63636364,
        525.72727273,  535.81818182,  545.90909091,  556.        ,
        566.09090909,  576.18181818,  586.27272727,  596.36363

In [30]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [33]:
a6=np.eye(4,5)

In [34]:
np.diagonal(a6)

array([1., 1., 1., 1.])

In [36]:
a7=np.arange(1,31)
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [37]:
a8=a7.reshape(6,5)

In [38]:
a8

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
a8.diagonal()

array([ 1,  7, 13, 19, 25])

In [40]:
a8.min()

1

In [41]:
a8.max()

30

In [42]:
a8.std() #mean

8.65544144839919

In [43]:
a8.sum()

465

In [45]:
a8.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351,
       378, 406, 435, 465], dtype=int32)

In [46]:
a8.T

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [47]:
a8.transpose()

array([[ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29],
       [ 5, 10, 15, 20, 25, 30]])

In [48]:
a8.dot(2) #it multiplies

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [49]:
a8.dot(3)

array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60],
       [63, 66, 69, 72, 75],
       [78, 81, 84, 87, 90]])

In [50]:
a8.argmin()

0

In [51]:
a8.argmax()

29

In [52]:
a8.prod()

1409286144

In [57]:
##saving array and loading array
n=np.array([[1,2],[6,7]])
n

array([[1, 2],
       [6, 7]])

In [56]:
n.shape

(1, 2, 2)

In [61]:
np.save("array n",n)

In [62]:
np.load("array n.npy")

array([[1, 2],
       [6, 7]])

In [63]:
np.exp(np.arange(1,11))

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [64]:
np.median(a8)

15.5

In [66]:
np.percentile(a8,3)

1.87

In [67]:
np.tan(2)

-2.185039863261519

In [68]:
np.tan(a8)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01],
       [ 3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01,  2.23716094e+00],
       [-1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
        -2.13489670e+00, -1.33526407e-01],
       [ 1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
         8.87142844e-01, -6.40533120e+00]])

In [69]:
np.cosec(a8)

AttributeError: module 'numpy' has no attribute 'cosec'

In [70]:
np.sin(a8)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175],
       [ 0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162]])

In [71]:
np.cos(a8)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206],
       [-0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281],
       [ 0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145]])

In [74]:
np.cosh(a8)

array([[1.54308063e+00, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
        7.42099485e+01],
       [2.01715636e+02, 5.48317035e+02, 1.49047916e+03, 4.05154203e+03,
        1.10132329e+04],
       [2.99370709e+04, 8.13773957e+04, 2.21206696e+05, 6.01302142e+05,
        1.63450869e+06],
       [4.44305526e+06, 1.20774764e+07, 3.28299846e+07, 8.92411505e+07,
        2.42582598e+08],
       [6.59407867e+08, 1.79245642e+09, 4.87240172e+09, 1.32445611e+10,
        3.60024497e+10],
       [9.78648047e+10, 2.66024120e+11, 7.23128532e+11, 1.96566715e+12,
        5.34323729e+12]])

In [75]:
np.sinh(a8)

array([[1.17520119e+00, 3.62686041e+00, 1.00178749e+01, 2.72899172e+01,
        7.42032106e+01],
       [2.01713157e+02, 5.48316123e+02, 1.49047883e+03, 4.05154190e+03,
        1.10132329e+04],
       [2.99370708e+04, 8.13773957e+04, 2.21206696e+05, 6.01302142e+05,
        1.63450869e+06],
       [4.44305526e+06, 1.20774764e+07, 3.28299846e+07, 8.92411505e+07,
        2.42582598e+08],
       [6.59407867e+08, 1.79245642e+09, 4.87240172e+09, 1.32445611e+10,
        3.60024497e+10],
       [9.78648047e+10, 2.66024120e+11, 7.23128532e+11, 1.96566715e+12,
        5.34323729e+12]])

In [76]:
np.tanh(a8)

array([[0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ],
       [0.99998771, 0.99999834, 0.99999977, 0.99999997, 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])

In [77]:
a9=np.arange(1,101)
a9[a9>60]

array([ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
        74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100])

In [78]:
a=a9>60

In [79]:
a

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [92]:

for i in range(65,91):
    print(chr(i),"--->",i)

A ---> 65
B ---> 66
C ---> 67
D ---> 68
E ---> 69
F ---> 70
G ---> 71
H ---> 72
I ---> 73
J ---> 74
K ---> 75
L ---> 76
M ---> 77
N ---> 78
O ---> 79
P ---> 80
Q ---> 81
R ---> 82
S ---> 83
T ---> 84
U ---> 85
V ---> 86
W ---> 87
X ---> 88
Y ---> 89
Z ---> 90


In [93]:
for i in range(65,91):
    if i%2==0:
        print(chr(i),"--->",i)

B ---> 66
D ---> 68
F ---> 70
H ---> 72
J ---> 74
L ---> 76
N ---> 78
P ---> 80
R ---> 82
T ---> 84
V ---> 86
X ---> 88
Z ---> 90


In [95]:
for i in range(65,91):
    if i%2==1:
        print(chr(i),"--->",i)

A ---> 65
C ---> 67
E ---> 69
G ---> 71
I ---> 73
K ---> 75
M ---> 77
O ---> 79
Q ---> 81
S ---> 83
U ---> 85
W ---> 87
Y ---> 89


In [99]:
print(ord('A'))

65


In [100]:
print(chr(78))

N


In [ ]:
import time,webbrowser
browsers=3
count=1
while count<=browsers:
    time.sleep(10)
    if count==1:
        webbrowser.open("http://apssdc.in")
    elif count==2:
        webbrowser.open("http://google.com")
    elif count==3:
        webbrowser.open("http://nrtec.ac.in")
    count=count+1
        